version: "3.2"

services:
  traefik:
    image: traefik:latest        
    networks:
      - proxy
    ports:
      # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
      - target: 80
        published: 80
        mode: host
      # Listen on port 443, default for HTTPS
      - target: 443
        published: 443
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-data/traefik.yml:/traefik.yml:ro
      - ./traefik-data/acme.json:/acme.json
      - ./traefik-data/configurations:/configurations
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.traefik-secure.entrypoints=websecure"
        # [REQUIRED] - THAY ĐỔI DOMAIN TRAEFIK
        - "traefik.http.routers.traefik-secure.rule=Host(`traefik.domain.com`)"
        - "traefik.http.routers.traefik-secure.middlewares=user-auth@file"
        - "traefik.http.routers.traefik-secure.service=api@internal"
        # Define the port inside of the Docker service to use
        - "traefik.http.services.traefik-public.loadbalancer.server.port=8080"

  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 9001
      LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:latest   
    networks:
      - proxy
      - agent_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.portainer-secure.entrypoints=websecure"
        # [REQUIRED] - THAY ĐỔI DOMAIN PORTAINER
        - "traefik.http.routers.portainer-secure.rule=Host(`portainer.domain.com`)"
        - "traefik.http.routers.portainer-secure.service=portainer"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  proxy:
    external: true
  agent_network:
    external: true
