api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

providers:
  docker:
    swarmMode: true
    exposedByDefault: false
  file:
    filename: /configurations/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      # [REQUIRED] - THAY ĐỔI EMAIL SỞ HỮU SSL
      email: mrchanvit@gmail.com
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web

accessLog:
  filePath: "/etc/traefik/access.log"
  bufferingSize: 100
